// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/proto/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DailyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyRequest) Reset() {
	*x = DailyRequest{}
	mi := &file_internal_proto_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyRequest) ProtoMessage() {}

func (x *DailyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyRequest.ProtoReflect.Descriptor instead.
func (*DailyRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *DailyRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type DailyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xml           string                 `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
	Valutes       []*Valute              `protobuf:"bytes,2,rep,name=valutes,proto3" json:"valutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyResponse) Reset() {
	*x = DailyResponse{}
	mi := &file_internal_proto_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyResponse) ProtoMessage() {}

func (x *DailyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyResponse.ProtoReflect.Descriptor instead.
func (*DailyResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *DailyResponse) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

func (x *DailyResponse) GetValutes() []*Valute {
	if x != nil {
		return x.Valutes
	}
	return nil
}

type Valute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumCode       string                 `protobuf:"bytes,2,opt,name=num_code,json=numCode,proto3" json:"num_code,omitempty"`
	CharCode      string                 `protobuf:"bytes,3,opt,name=char_code,json=charCode,proto3" json:"char_code,omitempty"`
	Nominal       int32                  `protobuf:"varint,4,opt,name=nominal,proto3" json:"nominal,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Valute) Reset() {
	*x = Valute{}
	mi := &file_internal_proto_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Valute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Valute) ProtoMessage() {}

func (x *Valute) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Valute.ProtoReflect.Descriptor instead.
func (*Valute) Descriptor() ([]byte, []int) {
	return file_internal_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Valute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Valute) GetNumCode() string {
	if x != nil {
		return x.NumCode
	}
	return ""
}

func (x *Valute) GetCharCode() string {
	if x != nil {
		return x.CharCode
	}
	return ""
}

func (x *Valute) GetNominal() int32 {
	if x != nil {
		return x.Nominal
	}
	return 0
}

func (x *Valute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Valute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_internal_proto_proto_proto protoreflect.FileDescriptor

const file_internal_proto_proto_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/proto.proto\x12\x05proto\"\"\n" +
	"\fDailyRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"J\n" +
	"\rDailyResponse\x12\x10\n" +
	"\x03xml\x18\x01 \x01(\tR\x03xml\x12'\n" +
	"\avalutes\x18\x02 \x03(\v2\r.proto.ValuteR\avalutes\"\x94\x01\n" +
	"\x06Valute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnum_code\x18\x02 \x01(\tR\anumCode\x12\x1b\n" +
	"\tchar_code\x18\x03 \x01(\tR\bcharCode\x12\x18\n" +
	"\anominal\x18\x04 \x01(\x05R\anominal\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value2H\n" +
	"\x0fCurrencyService\x125\n" +
	"\bGetDaily\x12\x13.proto.DailyRequest\x1a\x14.proto.DailyResponseB\x16Z\x14internal/proto;protob\x06proto3"

var (
	file_internal_proto_proto_proto_rawDescOnce sync.Once
	file_internal_proto_proto_proto_rawDescData []byte
)

func file_internal_proto_proto_proto_rawDescGZIP() []byte {
	file_internal_proto_proto_proto_rawDescOnce.Do(func() {
		file_internal_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_proto_proto_rawDesc), len(file_internal_proto_proto_proto_rawDesc)))
	})
	return file_internal_proto_proto_proto_rawDescData
}

var file_internal_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_proto_proto_goTypes = []any{
	(*DailyRequest)(nil),  // 0: proto.DailyRequest
	(*DailyResponse)(nil), // 1: proto.DailyResponse
	(*Valute)(nil),        // 2: proto.Valute
}
var file_internal_proto_proto_proto_depIdxs = []int32{
	2, // 0: proto.DailyResponse.valutes:type_name -> proto.Valute
	0, // 1: proto.CurrencyService.GetDaily:input_type -> proto.DailyRequest
	1, // 2: proto.CurrencyService.GetDaily:output_type -> proto.DailyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_proto_proto_init() }
func file_internal_proto_proto_proto_init() {
	if File_internal_proto_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_proto_proto_rawDesc), len(file_internal_proto_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_proto_proto_goTypes,
		DependencyIndexes: file_internal_proto_proto_proto_depIdxs,
		MessageInfos:      file_internal_proto_proto_proto_msgTypes,
	}.Build()
	File_internal_proto_proto_proto = out.File
	file_internal_proto_proto_proto_goTypes = nil
	file_internal_proto_proto_proto_depIdxs = nil
}
