// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/daily": {
            "get": {
                "description": "Генерирует XML по дате. Если date=error, возвращает 500",
                "produces": [
                    "text/xml"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "Получение XML курса валют",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Дата в формате DD-MM-YYYY",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пример ответа: XML Response",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Пример ответа: Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mock CBR API",
	Description:      "Мок-сервис, имитирующий ответы ЦБ РФ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
